---
apiVersion: v1
kind: Service
metadata:
  name: convert-audio-to-text-eng1
spec:
  selector:
    app: convert-audio-to-text-eng1
  type: NodePort
  ports:
  - name: protobuf-api
    port: 8556
    targetPort: 8061
