---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator
spec:
  selector:
    app: orchestrator
  type: NodePort
  ports:
  - name: mc-api
    nodePort: 30555
    port: 8061
    targetPort: 8061
