---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orchestrator
  labels:
    app: orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orchestrator
  template:
    metadata:
      labels:
        app: orchestrator
    spec:
      imagePullSecrets:
      - name: acumos-registry
      containers:
      - name: orchestrator
        image: cicd.ai4eu-dev.eu:7444/generic-parallel-orchestrator/orchestrator_container:1.2
        ports:
        - name: mc-api
          containerPort: 8061
        - name: webui
          containerPort: 8062
        volumeMounts:
        - mountPath: /logs
          name: logs
      restartPolicy: Always
      volumes:
      - name: logs
        hostPath:
          path: /var/acumos/log
